### ISSUE TITLE
roadmap to production

### ISSUE THREAD

**Issue by johnrfrank** [toshi-search/Toshi#100]
Toshi looks awesome.  We'd love to evaluate using Toshi in our product, so I'm wondering if there is a roadmap detailing major milestones toward changing the project tagline from "Note: This is far from production ready" to something like "Here are the benchmarks comparing Toshi, Elasticsearch, and Solr."

Are there any existing benchmarks?  Or more importantly, a guide to how we might be able to contribute?

Thanks for guidance, and sorry if I missed some obvious documentation about roadmap somewhere?

Also, is there a collaboration channel like IRC where Toshi developers hangout?

**Comment by hntd187** [comment]
Hi John,

There are no benchmarks that I'd want to publish right now, but there are benchmarks for the underlying indexing library that we use https://tantivy-search.github.io/bench/ I've been very cautious about talking / creating benchmarks mostly because I wanted to have an apples to apples comparison to use and I consider comparing single node clusters against one another to be a waste as the majority of ES uses cases rely on it's distributed nature. Also while I am optimistic we will be able to achieve performance similar or better than ES, I think it is unfair to discount the significant optimization work and maturity that ES has.

The roadmap I have in this project is woefully out of date and I'll be deleting it shortly as I've learned a lot about where I should take this project in that time. Namely that gaining true parity with ES's DSL and functionality just simply isn't going to happen, at least anytime soon. I'd rather take a subset of ES's functionality and do it very well and performant instead of worrying about having complete 1:1 coverage with ES. I haven't really identified where that subset should lie, but I'm open to discussions about what people are interested in and what people might want to see.

Finally, I haven't really outlined contribution areas mostly because it's been mostly me writing a lot of the code up until this point, but that doesn't mean there isn't a lot of places where people can pitch in, in both advanced topics and also relatively lightweight tasks that should suit anyone. We've also doubled down on some newer libraries and communities inside the rust ecosystem, namely tower that will both power a lot of Toshi's backend services, but I hope to also be able to contribute a lot to tower in general as a result of my applied work here.

We also hang out here https://gitter.im/toshi-search/Lobby on gitter, chat ranges from me complaining about the compiler to me complaining about video games. We also occasionally talk about the actual project.

**Comment by peterbe** [comment]
I truly appreciate not trying *"[gain] true parity with ES's DSL and functionality"*.
But it certainly would be really interesting to see what features are planned and to track them. 
For example, I care about synonyms, fragment extraction, and suggestions. I don't care that much about clustering, sharding, or aggregates. (thinking here much in terms of ES, not Tantivy).

**Comment by hntd187** [comment]
@peterbe if you care more about indexing related things you might be better placed in contributing to Tantivy, clustering and all that jazz is server related things to architecture. Ideally as Tantivy expands it's functionality we'll also try and get that functionality exposed to the indexes. Paging @fulmicoton if he wants to speak to any of that, but yea.

**Comment by corbinu** [comment]
@hntd187 Another area you might look for insperation is Couchbase: https://docs.couchbase.com/server/6.0/fts/full-text-intro.html My company switched from elastic to their full text search last year and have found it much easier to work with. 

Super excited to see this project!
