### ISSUE TITLE
Investigate aggregates

### ISSUE THREAD

**Issue by fhaynes** [toshi-search/Toshi#13]

**Comment by hntd187** [comment]
@fulmicoton perhaps has some insight on the Tantivy level for this. I believe this could be done via an implemented query from Tantivy's API

**Comment by fulmicoton** [comment]
I suspect it's more a collector than a query... But I would love to see more text in the  description of this issue to be able to reply in a smarter manner

**Comment by hntd187** [comment]
Yea, it's probably a bit of both @fulmicoton but now that you mention it it does make more sense for it to be on the collector. 

So for example, you have an `u64` fast field and you want to sum them. So ES has 2 things that it can do here, metric and bucket aggregation. Metric aggregation is just the aggregation across the entire set, so in this case the entire sum across all documents. The second will first bucket documents based on some criteria, range, date, some arbitrary filter, and then you can apply a metric aggregation to these buckets themselves, giving you a per bucket aggregation.

It seems reasonable to start off simple with this, but it appears to me that these aggregates can go into a looney amount of depth, so I'd imagine we should design for aggregates that can be composed together.

**Comment by stephanbuys** [comment]
@hntd187 we have some functionality in `elastic-rs` that will take a an aggregation result and turn it into a table/stream of results - this might be an interesting reference (you are correct - a loony amount of depth is possible)

**Comment by hntd187** [comment]
@stephanbuys hey thanks for the link and hello! Reading this and having worked with ES Aggregates before it almost makes sense to me to either do 1 of 2 things. Make these aggregates some kind of composable AST that can then be evaluated in order to come to whatever the end value is, that way there are 2 steps of building (Map) the AST and then reducing it all back down, but its easy to understand, composable and would handle N level depth.

My second idea is just not allow endless depth, that is even easier and not prone to the lunacy with the nested query depth, but obviously is limited to only those levels. This will also have to be distributed, so I basically don't want to build an accidental distributed execution engine based on tantivy.
