### ISSUE TITLE
Add some aggregation metrics

### ISSUE THREAD

**Issue by degharbi** [toshi-search/Toshi#474]
Hi folks, 

I just started using Toshi, and it would be really nice to add some aggregations metrics like: count, mean, sum...

I would dev myself but i'm not a at all a Rust dev (maybe i'll start soon :) ). 

Thanks,

**Comment by hntd187** [comment]
I had an initial implementation of this that I since removed because at the time it was possible in tantivy, but not very pretty code. Now tantivy has it's custom collectors API making this a lot easier. Currently my list of impl things are

1. Async/await, I'd like a stable release version of hyper and tokio for this
2. Raft/WAL/Storage Layer for cluster based on Baynard's impl of it with extensions
3. Aggregation and Metrics
