### ISSUE TITLE
How to sort search?

### ISSUE THREAD

**Issue by Jonarod** [toshi-search/Toshi#491]
If RE-indexing is not supported (#490 ) I wonder how to properly sort a search result?

In fact, I understand I can create multiple indexes for each sort order I need (e.g: `my_index_asc`, `my_index_desc`), however that means I should be adding new documents in the correct order which is not realistic.

That being said, I don't get the `limit` option on queries if that does not come with a sorting instruction. Maybe I misunderstood something, can someone shed some lights on this ?

Thanks :)

**Comment by hntd187** [comment]
No I don't think you misunderstood it, limit it exactly what it sounds like it's meant to limit the results, not sort them. That being said you currently can't sort results by a field. It shouldn't be hard to add results sorting though, I know lucene has sorting criteria for it's results so conceivably it might be something to implement in tantivy, but also it'd be straight forward to add in toshi itself.

**Comment by Jonarod** [comment]
If Toshi is meant only for full-text search, I understand scoring is the
only important sorting mechanism. However once we introduce the notion of
"query", it is hard to avoid classic sort.

I see Toshi is the result of a lot of optimizations to cut through all
bottlenecks including from the choice of Rust itself which is fast by
design. Forcing one to do its own sorting after all this chain of
optimizations would clearly be the bottleneck, defeating the purpose of
Toshi I think...

Thinking out loud here, off the bat I can see that memory usage would
explode if one scans though 5M entries to sort them one by one. Plus,
threads misuse might eventually block new searches etc... A lot of issues I
can foresee.

IMHO, I would see a better solution like this:

- create an index with a sortable field: in the schema, one specifies
something like `sortby:{field:date, order:asc}`
- at commit, the index would be reordered by the selected constraint.
Alternatively, one could optimize the re-ordering calls and manually choose
when to do so instead. For example using a new command to force re-ordering
the index based on the sortby constraint: `
http://localhost:8080/myIndexDateAsc/refresh`
- when querying, one specifies if it prefers to override scoring in favor
of current index order `query:{terms:{...}, useSortBy:true}`

This workflow would be a bit more optimized than performing sort at each
query... No calculations is needed at query time since the index comes
pre-sorted. The drawback would clearly be that data needs to be
denormalized in multiple indexes to support multiple sorting options. But
since Toshi is rather meant for search speed, IMO it's reasonable.

Anyways I talk a lot but I am not able to help further in action as I am no
Rust dev at all :(

Unfortunately I will have to pick another framework for my specific use
case as I don't see good perfs coming by sorting through millions of
entries at each query, but I'd love to give it a shot when this feature
comes out :)

**Comment by hntd187** [comment]
I totally understand, even if you don't end up using toshi it's very helpful insight so I know what people are expecting to be able to do. And I agree while scoring is the most "search engine" esq thing here at the same time there are significant amounts of workflows that don't care about score as much as they care about the ordering based on specific fields. Just to answer some of your points here
1. the index creation you speak about would have to happen in tantivy, I am trying my best not to implement functionality that should live in tantivy, but with that having been said there is no reason toshi cannot sort results from tantivy. I believe it's rather simple to implement and I can't imagine it being a gigantic performance hit unless you are sorting a very large amount of results. 
2 and 3. I don't know if I follow what the benefit might be of having an index pre-sorted, documents  are stored in a reverse index in tantivy so that might be hard to do or require some rearchitecting.

Either way, I think in the short term it makes a ton of sense to add something like a "sortBy" option and an "order" option to give simple sorting, that way if you had a field you wanted to sort by after scoring was done you could trivially do that. It's not a complete option, but it's a start as more tantivy features would have to be implemented and it's likely some work to get to a good level of parity with lucene. Does that sound reasonable?

Also don't worry about being/not being a rust developer your feedback is very much appreciated and it's very helpful to me to see people using toshi and telling me what they want to see, so thanks. :-)

**Comment by hntd187** [comment]
Actually following up on this, you can sort by fast fields in the schema already, it's not exposed though through the API, I can add it pretty easily.

**Comment by Jonarod** [comment]
That would be great. I didn't see that on tantivy either though...

**Comment by hntd187** [comment]
It would be right [here](https://docs.rs/tantivy/0.10.3/tantivy/collector/struct.TopDocs.html#method.order_by_u64_field). I had to ask myself. Note this only works on integer fast fields, I'll have something in for this shortly.

**Comment by hntd187** [comment]
I pushed a commit for this, you should be able to do this kind of request on a fast field

```json
{
	"query": {
		"term": {
			"lyrics": "baby"
		}
	},
	"sort_by": "year"
}
```

**Comment by Jonarod** [comment]
Nice thank you for this!
I'll give it a try tonight or tomorrow.
Maybe I can live with that by calculating a number based on the text field
I have. Will check.
